### ISSUE TITLE
04.0 - BACK - Initialization

### ISSUE THREAD

**Issue by kiw808** [WildCodeSchool/2109-wns-remote2-excelant#1]
-----------------------------------------------------------------------------------
##### Todo list
- [x] Initialiser le projet
- [x] Ajouter les dépendences (typescript, graphql, mongoose, apollo/server)
- [x] Push initial
- [x] Configurer eslint et prettier
- [x] Configurer typescript
