### ISSUE TITLE
04.0 - FRONT - Initialization

### ISSUE THREAD

**Issue by AmanelGau** [WildCodeSchool/2109-wns-remote2-excelant#2]
-----------------------------------------------------------------------------------
##### Todo list
- [x] Créer application react
- [x] Ajouter les dépendences (typescript, scss, tailwind, graphql, materialUi, apollo/client)
- [x] Push initial
- [x] Configurer eslint et prettier
- [x] Configurer typescript
