### ISSUE TITLE
#### 02 - Mise en place du système de login

### ISSUE THREAD

**Issue by Lionel21** [WildCodeSchool/2109-wns-remote2-excelant#25]
-----------------------------------------------------------------------------------
##### Todo list
- [ ] Création d'un formulaire
- [ ] Création d'un système de login
- [ ] Création d'un système de réinitialisation du mot de passe
